<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SurahSeeder extends Seeder
{
    public function run(): void
    {
        $surahs = [
            ['number' => 1, 'name' => 'سورة الفاتحة', 'aya_count' => 7],
            ['number' => 2, 'name' => 'سورة البقرة', 'aya_count' => 286],
            ['number' => 3, 'name' => 'سورة آل عمران', 'aya_count' => 200],
            ['number' => 4, 'name' => 'سورة النساء', 'aya_count' => 176],
            ['number' => 5, 'name' => 'سورة المائدة', 'aya_count' => 120],
            ['number' => 6, 'name' => 'سورة الأنعام', 'aya_count' => 165],
            ['number' => 7, 'name' => 'سورة الأعراف', 'aya_count' => 206],
            ['number' => 8, 'name' => 'سورة الأنفال', 'aya_count' => 75],
            ['number' => 9, 'name' => 'سورة التوبة', 'aya_count' => 129],
            ['number' => 10, 'name' => 'سورة يونس', 'aya_count' => 109],
            ['number' => 11, 'name' => 'سورة هود', 'aya_count' => 123],
            ['number' => 12, 'name' => 'سورة يوسف', 'aya_count' => 111],
            ['number' => 13, 'name' => 'سورة الرعد', 'aya_count' => 43],
            ['number' => 14, 'name' => 'سورة إبراهيم', 'aya_count' => 52],
            ['number' => 15, 'name' => 'سورة الحجر', 'aya_count' => 99],
            ['number' => 16, 'name' => 'سورة النحل', 'aya_count' => 128],
            ['number' => 17, 'name' => 'سورة الإسراء', 'aya_count' => 111],
            ['number' => 18, 'name' => 'سورة الكهف', 'aya_count' => 110],
            ['number' => 19, 'name' => 'سورة مريم', 'aya_count' => 98],
            ['number' => 20, 'name' => 'سورة طه', 'aya_count' => 135],
            ['number' => 21, 'name' => 'سورة الأنبياء', 'aya_count' => 112],
            ['number' => 22, 'name' => 'سورة الحج', 'aya_count' => 78],
            ['number' => 23, 'name' => 'سورة المؤمنون', 'aya_count' => 118],
            ['number' => 24, 'name' => 'سورة النور', 'aya_count' => 64],
            ['number' => 25, 'name' => 'سورة الفرقان', 'aya_count' => 77],
            ['number' => 26, 'name' => 'سورة الشعراء', 'aya_count' => 227],
            ['number' => 27, 'name' => 'سورة النمل', 'aya_count' => 93],
            ['number' => 28, 'name' => 'سورة القصص', 'aya_count' => 88],
            ['number' => 29, 'name' => 'سورة العنكبوت', 'aya_count' => 69],
            ['number' => 30, 'name' => 'سورة الروم', 'aya_count' => 60],
            ['number' => 31, 'name' => 'سورة لقمان', 'aya_count' => 34],
            ['number' => 32, 'name' => 'سورة السجدة', 'aya_count' => 30],
            ['number' => 33, 'name' => 'سورة الأحزاب', 'aya_count' => 73],
            ['number' => 34, 'name' => 'سورة سبأ', 'aya_count' => 54],
            ['number' => 35, 'name' => 'سورة فاطر', 'aya_count' => 45],
            ['number' => 36, 'name' => 'سورة يس', 'aya_count' => 83],
            ['number' => 37, 'name' => 'سورة الصافات', 'aya_count' => 182],
            ['number' => 38, 'name' => 'سورة ص', 'aya_count' => 88],
            ['number' => 39, 'name' => 'سورة الزمر', 'aya_count' => 75],
            ['number' => 40, 'name' => 'سورة غافر', 'aya_count' => 85],
            ['number' => 41, 'name' => 'سورة فصلت', 'aya_count' => 54],
            ['number' => 42, 'name' => 'سورة الشورى', 'aya_count' => 53],
            ['number' => 43, 'name' => 'سورة الزخرف', 'aya_count' => 89],
            ['number' => 44, 'name' => 'سورة الدخان', 'aya_count' => 59],
            ['number' => 45, 'name' => 'سورة الجاثية', 'aya_count' => 37],
            ['number' => 46, 'name' => 'سورة الأحقاف', 'aya_count' => 35],
            ['number' => 47, 'name' => 'سورة محمد', 'aya_count' => 38],
            ['number' => 48, 'name' => 'سورة الفتح', 'aya_count' => 29],
            ['number' => 49, 'name' => 'سورة الحجرات', 'aya_count' => 18],
            ['number' => 50, 'name' => 'سورة ق', 'aya_count' => 45],
            ['number' => 51, 'name' => 'سورة الذاريات', 'aya_count' => 60],
            ['number' => 52, 'name' => 'سورة الطور', 'aya_count' => 49],
            ['number' => 53, 'name' => 'سورة النجم', 'aya_count' => 62],
            ['number' => 54, 'name' => 'سورة القمر', 'aya_count' => 55],
            ['number' => 55, 'name' => 'سورة الرحمن', 'aya_count' => 78],
            ['number' => 56, 'name' => 'سورة الواقعة', 'aya_count' => 96],
            ['number' => 57, 'name' => 'سورة الحديد', 'aya_count' => 29],
            ['number' => 58, 'name' => 'سورة المجادلة', 'aya_count' => 22],
            ['number' => 59, 'name' => 'سورة الحشر', 'aya_count' => 24],
            ['number' => 60, 'name' => 'سورة الممتحنة', 'aya_count' => 13],
            ['number' => 61, 'name' => 'سورة الصف', 'aya_count' => 14],
            ['number' => 62, 'name' => 'سورة الجمعة', 'aya_count' => 11],
            ['number' => 63, 'name' => 'سورة المنافقون', 'aya_count' => 11],
            ['number' => 64, 'name' => 'سورة التغابن', 'aya_count' => 18],
            ['number' => 65, 'name' => 'سورة الطلاق', 'aya_count' => 12],
            ['number' => 66, 'name' => 'سورة التحريم', 'aya_count' => 12],
            ['number' => 67, 'name' => 'سورة الملك', 'aya_count' => 30],
            ['number' => 68, 'name' => 'سورة القلم', 'aya_count' => 52],
            ['number' => 69, 'name' => 'سورة الحاقة', 'aya_count' => 52],
            ['number' => 70, 'name' => 'سورة المعارج', 'aya_count' => 44],
            ['number' => 71, 'name' => 'سورة نوح', 'aya_count' => 28],
            ['number' => 72, 'name' => 'سورة الجن', 'aya_count' => 28],
            ['number' => 73, 'name' => 'سورة المزمل', 'aya_count' => 20],
            ['number' => 74, 'name' => 'سورة المدثر', 'aya_count' => 56],
            ['number' => 75, 'name' => 'سورة القيامة', 'aya_count' => 40],
            ['number' => 76, 'name' => 'سورة الإنسان', 'aya_count' => 31],
            ['number' => 77, 'name' => 'سورة المرسلات', 'aya_count' => 50],
            ['number' => 78, 'name' => 'سورة النبأ', 'aya_count' => 40],
            ['number' => 79, 'name' => 'سورة النازعات', 'aya_count' => 46],
            ['number' => 80, 'name' => 'سورة عبس', 'aya_count' => 42],
            ['number' => 81, 'name' => 'سورة التكوير', 'aya_count' => 29],
            ['number' => 82, 'name' => 'سورة الانفطار', 'aya_count' => 19],
            ['number' => 83, 'name' => 'سورة المطففين', 'aya_count' => 36],
            ['number' => 84, 'name' => 'سورة الانشقاق', 'aya_count' => 25],
            ['number' => 85, 'name' => 'سورة البروج', 'aya_count' => 22],
            ['number' => 86, 'name' => 'سورة الطارق', 'aya_count' => 17],
            ['number' => 87, 'name' => 'سورة الأعلى', 'aya_count' => 19],
            ['number' => 88, 'name' => 'سورة الغاشية', 'aya_count' => 26],
            ['number' => 89, 'name' => 'سورة الفجر', 'aya_count' => 30],
            ['number' => 90, 'name' => 'سورة البلد', 'aya_count' => 20],
            ['number' => 91, 'name' => 'سورة الشمس', 'aya_count' => 15],
            ['number' => 92, 'name' => 'سورة الليل', 'aya_count' => 21],
            ['number' => 93, 'name' => 'سورة الضحى', 'aya_count' => 11],
            ['number' => 94, 'name' => 'سورة الشرح', 'aya_count' => 8],
            ['number' => 95, 'name' => 'سورة التين', 'aya_count' => 8],
            ['number' => 96, 'name' => 'سورة العلق', 'aya_count' => 19],
            ['number' => 97, 'name' => 'سورة القدر', 'aya_count' => 5],
            ['number' => 98, 'name' => 'سورة البينة', 'aya_count' => 8],
            ['number' => 99, 'name' => 'سورة الزلزلة', 'aya_count' => 8],
            ['number' => 100, 'name' => 'سورة العاديات', 'aya_count' => 11],
            ['number' => 101, 'name' => 'سورة القارعة', 'aya_count' => 11],
            ['number' => 102, 'name' => 'سورة التكاثر', 'aya_count' => 8],
            ['number' => 103, 'name' => 'سورة العصر', 'aya_count' => 3],
            ['number' => 104, 'name' => 'سورة الهمزة', 'aya_count' => 9],
            ['number' => 105, 'name' => 'سورة الفيل', 'aya_count' => 5],
            ['number' => 106, 'name' => 'سورة قريش', 'aya_count' => 4],
            ['number' => 107, 'name' => 'سورة الماعون', 'aya_count' => 7],
            ['number' => 108, 'name' => 'سورة الكوثر', 'aya_count' => 3],
            ['number' => 109, 'name' => 'سورة الكافرون', 'aya_count' => 6],
            ['number' => 110, 'name' => 'سورة النصر', 'aya_count' => 3],
            ['number' => 111, 'name' => 'سورة المسد', 'aya_count' => 5],
            ['number' => 112, 'name' => 'سورة الإخلاص', 'aya_count' => 4],
            ['number' => 113, 'name' => 'سورة الفلق', 'aya_count' => 5],
            ['number' => 114, 'name' => 'سورة الناس', 'aya_count' => 6],
        ];

        DB::table('surah')->insert($surahs);
    }
}
